// Generated by scripts/build-client.mjs from src/client.tsx — do not edit.
window.__ModuleLoader__.load({
  id: "dsh-auto-archive",
  factory: (require) => {
    var module = { exports: {} };
    var exports = module.exports;
    Object.defineProperty(exports, Symbol.toStringTag, { value: "Module" });
    "use strict";
    var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
        if (k2 === undefined) k2 = k;
        var desc = Object.getOwnPropertyDescriptor(m, k);
        if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
          desc = { enumerable: true, get: function() { return m[k]; } };
        }
        Object.defineProperty(o, k2, desc);
    }) : (function(o, m, k, k2) {
        if (k2 === undefined) k2 = k;
        o[k2] = m[k];
    }));
    var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
        Object.defineProperty(o, "default", { enumerable: true, value: v });
    }) : function(o, v) {
        o["default"] = v;
    });
    var __importStar = (this && this.__importStar) || (function () {
        var ownKeys = function(o) {
            ownKeys = Object.getOwnPropertyNames || function (o) {
                var ar = [];
                for (var k in o) if (Object.prototype.hasOwnProperty.call(o, k)) ar[ar.length] = k;
                return ar;
            };
            return ownKeys(o);
        };
        return function (mod) {
            if (mod && mod.__esModule) return mod;
            var result = {};
            if (mod != null) for (var k = ownKeys(mod), i = 0; i < k.length; i++) if (k[i] !== "default") __createBinding(result, mod, k[i]);
            __setModuleDefault(result, mod);
            return result;
        };
    })();
    Object.defineProperty(exports, "__esModule", { value: true });
    exports.inject = void 0;
    exports.apply = apply;
    /**
     * Browser half of the archived-sessions page (@muwinds/dsh-archived-sessions).
     *
     * Runs inside the harness web profile's __ModuleLoader__ bundle: this module is
     * compiled to CommonJS by `tsc -p tsconfig.client.json` and then wrapped into
     * `window.__ModuleLoader__.load({ id, factory: (require) => {...} })` by
     * scripts/build-client.mjs. The compiled body may use `require` and `exports`
     * freely because both are in scope inside the factory.
     */
    const React = __importStar(require("react"));
    // ---------------------------------------------------------------------------
    // Styles
    // ---------------------------------------------------------------------------
    const CSS = [
        ".dsw-arch-page{font-size:13px;padding:2px 2px 24px;}",
        ".dsw-arch-toolbar{display:flex;align-items:center;gap:10px;flex-wrap:wrap;margin-bottom:10px;}",
        ".dsw-arch-page-title{font-weight:600;color:var(--dsw-alias-label-primary);}",
        ".dsw-arch-meta{color:var(--dsw-alias-label-secondary);font-size:12px;}",
        ".dsw-arch-btn{background:transparent;border:1px solid var(--dsw-alias-border-l2);color:var(--dsw-alias-label-primary);border-radius:6px;padding:3px 7px;font-size:12px;cursor:pointer;margin-right:4px;white-space:nowrap;}",
        ".dsw-arch-btn:hover:not(:disabled){border-color:var(--dsw-alias-brand-primary);color:var(--dsw-alias-brand-primary);}",
        ".dsw-arch-btn-danger{color:var(--dsw-alias-state-error-primary);border-color:var(--dsw-alias-state-error-primary);}",
        ".dsw-arch-btn:disabled{opacity:0.45;cursor:default;}",
        ".dsw-arch-table{width:100%;border-collapse:collapse;table-layout:fixed;}",
        ".dsw-arch-table th{text-align:left;font-weight:600;color:var(--dsw-alias-label-secondary);font-size:12px;padding:6px 8px;border-bottom:1px solid var(--dsw-alias-border-l1);}",
        ".dsw-arch-table td{padding:8px 8px;border-bottom:1px solid var(--dsw-alias-border-l1);vertical-align:top;}",
        ".dsw-arch-table tr:last-child td{border-bottom:none;}",
        ".dsw-arch-table th:nth-child(1),.dsw-arch-table td:nth-child(1){width:32px;text-align:center;padding-left:2px;padding-right:2px;}",
        ".dsw-arch-table th:nth-child(2),.dsw-arch-table td:nth-child(2){width:auto;}",
        ".dsw-arch-table th:nth-child(3),.dsw-arch-table td:nth-child(3){width:104px;}",
        ".dsw-arch-table th:nth-child(4),.dsw-arch-table td:nth-child(4){width:92px;padding-left:2px;padding-right:2px;}",
        ".dsw-arch-size{white-space:nowrap;}",
        ".dsw-arch-actions{white-space:nowrap;}",
        ".dsw-arch-title-click{cursor:pointer;color:var(--dsw-alias-label-primary);}",
        ".dsw-arch-title-click:hover{text-decoration:underline;}",
        ".dsw-arch-id,.dsw-arch-path{font-family:ui-monospace,SFMono-Regular,Consolas,monospace;font-size:11px;color:var(--dsw-alias-label-secondary);word-break:break-all;margin-top:2px;}",
        ".dsw-arch-selectbar{display:flex;align-items:center;gap:8px;padding:6px 10px;margin-bottom:10px;background:var(--dsw-alias-bg-layer-1);border:1px solid var(--dsw-alias-border-l1);border-radius:8px;font-size:12px;flex-wrap:wrap;}",
        ".dsw-arch-selectbar .dsw-arch-meta{flex:1;}",
        ".dsw-arch-detail{background:var(--dsw-alias-bg-layer-1);border:1px solid var(--dsw-alias-border-l1);border-radius:8px;padding:10px 12px;font-size:12px;text-align:left;}",
        ".dsw-arch-detail-head{margin-bottom:8px;}",
        ".dsw-arch-detail-body{max-height:360px;overflow:auto;}",
        ".dsw-arch-msg{margin-bottom:8px;white-space:pre-wrap;word-break:break-word;}",
        ".dsw-arch-msg-role{display:inline-block;font-weight:600;margin-right:6px;}",
        ".dsw-arch-msg-user .dsw-arch-msg-role{color:var(--dsw-alias-label-primary);}",
        ".dsw-arch-msg-assistant .dsw-arch-msg-role{color:var(--dsw-alias-brand-primary);}",
        ".dsw-arch-msg-tool .dsw-arch-msg-role{color:var(--dsw-alias-state-warn-primary);}",
        ".dsw-arch-msg-time{color:var(--dsw-alias-label-secondary);font-size:11px;margin-left:6px;}",
        ".dsw-arch-detail-note{color:var(--dsw-alias-label-secondary);font-size:11px;margin-bottom:8px;}",
        ".dsw-arch-error{color:var(--dsw-alias-state-error-primary);font-size:12px;margin-bottom:8px;}",
        ".dsw-arch-empty{color:var(--dsw-alias-label-secondary);padding:28px 0;text-align:center;}",
        ".dsw-arch-badge{display:inline-block;border:1px solid var(--dsw-alias-state-warn-primary);color:var(--dsw-alias-state-warn-primary);border-radius:4px;padding:1px 6px;font-size:11px;}",
        ".dsw-auto-card{background:var(--dsw-alias-bg-layer-1);border:1px solid var(--dsw-alias-border-l1);border-radius:8px;padding:10px 12px;margin-bottom:12px;font-size:12px;}",
        ".dsw-auto-head{display:flex;align-items:center;gap:10px;flex-wrap:wrap;margin-bottom:6px;}",
        ".dsw-auto-title{font-weight:600;color:var(--dsw-alias-label-primary);font-size:13px;}",
        ".dsw-auto-row{display:flex;align-items:center;gap:8px;flex-wrap:wrap;margin:6px 0;}",
        ".dsw-auto-input{background:var(--dsw-alias-bg-input,transparent);border:1px solid var(--dsw-alias-border-l2);color:var(--dsw-alias-label-primary);border-radius:6px;padding:3px 6px;font-size:12px;width:64px;}",
        ".dsw-auto-status{color:var(--dsw-alias-label-secondary);margin:4px 0;}",
        ".dsw-auto-preview{margin-top:6px;border-top:1px dashed var(--dsw-alias-border-l1);padding-top:6px;}",
        ".dsw-auto-preview-item{display:flex;gap:8px;align-items:baseline;padding:2px 0;}",
        ".dsw-auto-preview-title{color:var(--dsw-alias-label-primary);overflow:hidden;text-overflow:ellipsis;white-space:nowrap;flex:1;}",
        ".dsw-auto-preview-idle{color:var(--dsw-alias-label-secondary);white-space:nowrap;}",
        ".dsw-auto-sesslist{margin-top:8px;border-top:1px solid var(--dsw-alias-border-l1);padding-top:8px;max-height:320px;overflow:auto;}",
        ".dsw-auto-sess{display:flex;gap:8px;align-items:center;padding:3px 0;font-size:12px;}",
        ".dsw-auto-sess-title{color:var(--dsw-alias-label-primary);overflow:hidden;text-overflow:ellipsis;white-space:nowrap;flex:1;}",
        ".dsw-auto-sess-meta{color:var(--dsw-alias-label-secondary);white-space:nowrap;font-size:11px;}",
        ".dsw-auto-sess-btns{white-space:nowrap;}"
    ].join("");
    // 样式不再注入 document.head：官方壳更新后设置页的渲染环境可能隔离
    // （Shadow DOM / CSP 清理），head 注入会整体失效——样式改为随组件树渲染，
    // 见 ArchivedSessionsPage 根节点内的 <style>，卸载随组件自动移除。
    // ---------------------------------------------------------------------------
    // API
    // ---------------------------------------------------------------------------
    function api(action, args) {
        return fetch("/dsh-archived/" + action, {
            method: "POST",
            headers: { "content-type": "application/json" },
            body: JSON.stringify(args || {})
        })
            .then((res) => res.json().catch(() => null))
            .then((payload) => {
            if (payload === null || typeof payload !== "object") {
                throw new Error("请求失败：服务返回了无效响应");
            }
            if ("error" in payload && typeof payload.error === "string") {
                throw new Error(payload.error);
            }
            return payload;
        });
    }
    // ---------------------------------------------------------------------------
    // Formatting
    // ---------------------------------------------------------------------------
    function fmtSize(bytes) {
        const n = Number(bytes) || 0;
        if (n <= 0)
            return "0 B";
        const units = ["B", "KB", "MB", "GB", "TB"];
        let v = n;
        let i = 0;
        while (v >= 1024 && i < units.length - 1) {
            v = v / 1024;
            i = i + 1;
        }
        return (i === 0 ? String(Math.round(v)) : v.toFixed(1)) + " " + units[i];
    }
    function fmtTime(ms) {
        if (!ms)
            return "—";
        try {
            return new Date(ms).toLocaleString();
        }
        catch (e) {
            return String(ms);
        }
    }
    /** Whole days since `ms`, floored at zero (for compact "N 天前" labels). */
    function daysAgo(ms) {
        if (!ms)
            return null;
        return Math.max(0, Math.floor((Date.now() - ms) / 86400000));
    }
    // ---------------------------------------------------------------------------
    // Auto-archive settings card
    // ---------------------------------------------------------------------------
    /**
     * Self-contained settings card for the background auto-archiver. Owns its
     * fetching state so the main archive list stays independent; `onChanged` lets
     * the parent reload after a live scan moved sessions into the archive.
     */
    function AutoArchiveCard({ onChanged }) {
        const [loaded, setLoaded] = React.useState(false);
        const [status, setStatus] = React.useState(null);
        const [enabled, setEnabled] = React.useState(false);
        const [idleDays, setIdleDays] = React.useState("14");
        // Display unit is DAYS; the stored config stays in minutes (1 day = 1440).
        const [intervalDays, setIntervalDays] = React.useState("1");
        const [busy, setBusy] = React.useState(null);
        const [error, setError] = React.useState(null);
        const [notice, setNotice] = React.useState(null);
        const [showPreview, setShowPreview] = React.useState(false);
        const [scanArmed, setScanArmed] = React.useState(false);
        const [showSessions, setShowSessions] = React.useState(false);
        const [sessions, setSessions] = React.useState(null);
        const [sessBusy, setSessBusy] = React.useState(null);
        const [delArmId, setDelArmId] = React.useState(null);
        function minutesToDays(minutes) {
            const days = Math.round((minutes / 1440) * 100) / 100;
            return String(days);
        }
        function describe(err) {
            if (err && typeof err === "object" && typeof err.message === "string") {
                return err.message;
            }
            return String(err);
        }
        function load() {
            api("auto-status", {})
                .then((res) => {
                setStatus(res);
                if (res && res.config) {
                    setEnabled(!!res.config.enabled);
                    setIdleDays(String(res.config.idleDays));
                    setIntervalDays(minutesToDays(res.config.intervalMinutes));
                }
                setLoaded(true);
            })
                .catch((err) => {
                setError(describe(err));
                setLoaded(true);
            });
        }
        React.useEffect(() => {
            load();
            // eslint-disable-next-line react-hooks/exhaustive-deps
        }, []);
        function save(nextEnabled) {
            setBusy("save");
            setError(null);
            setNotice(null);
            const payload = {
                enabled: nextEnabled,
                idleDays: Math.max(0.5, Number(idleDays) || 14),
                intervalMinutes: Math.max(0.25, Number(intervalDays) || 1) * 1440
            };
            api("auto-config-set", payload)
                .then((res) => {
                if (res && res.config) {
                    setEnabled(!!res.config.enabled);
                    setIdleDays(String(res.config.idleDays));
                    setIntervalDays(minutesToDays(res.config.intervalMinutes));
                }
                setNotice(nextEnabled ? "自动归档已开启" : "自动归档已关闭");
                setBusy(null);
                load();
            })
                .catch((err) => {
                setError(describe(err));
                setBusy(null);
            });
        }
        // ---- manual per-session operations ----
        function loadSessions() {
            setSessBusy("load");
            api("auto-sessions", {})
                .then((res) => {
                setSessions(Array.isArray(res.items) ? res.items : []);
                setSessBusy(null);
            })
                .catch((err) => {
                setError(describe(err));
                setSessBusy(null);
            });
        }
        function toggleSessions() {
            const next = !showSessions;
            setShowSessions(next);
            if (next && sessions === null)
                loadSessions();
        }
        function archiveOneNow(id) {
            setSessBusy("archive:" + id);
            setError(null);
            api("auto-archive-one", { sessionId: id })
                .then(() => {
                setNotice("已归档 1 个会话");
                loadSessions();
                onChanged();
            })
                .catch((err) => setError(describe(err)))
                .finally(() => setSessBusy(null));
        }
        function setExcludedNow(id, add) {
            setSessBusy("exclude:" + id);
            setError(null);
            api("auto-exclude", { sessionId: id, add })
                .then(() => loadSessions())
                .catch((err) => setError(describe(err)))
                .finally(() => setSessBusy(null));
        }
        // 两步确认的删除：删除 → 确认（5 秒后自动取消），与归档列表的删除同款交互
        function armDelete(id) {
            setDelArmId(id);
            try {
                window.setTimeout(() => {
                    setDelArmId((cur) => (cur === id ? null : cur));
                }, 5000);
            }
            catch (e) {
                // timer 不可用时保持待确认状态
            }
        }
        function deleteOneNow(id) {
            setSessBusy("delete:" + id);
            setError(null);
            api("auto-delete-one", { sessionId: id })
                .then(() => {
                setNotice("已删除 1 个会话（含日志文件，不可恢复）");
                setDelArmId(null);
                loadSessions();
                onChanged();
            })
                .catch((err) => setError(describe(err)))
                .finally(() => setSessBusy(null));
        }
        function runScan(dryRun) {
            setBusy(dryRun ? "preview" : "scan");
            setError(null);
            setNotice(null);
            api("auto-scan", { dryRun })
                .then((res) => {
                const count = res && Array.isArray(res.archived) ? res.archived.length : 0;
                setNotice(dryRun
                    ? "预览完成：当前有 " + (res && res.preview ? res.preview.length : 0) + " 个闲置会话待归档"
                    : "扫描完成：已归档 " + count + " 个会话" + (res && res.errors && res.errors.length > 0 ? "，" + res.errors.length + " 个失败" : ""));
                setScanArmed(false);
                setShowPreview(dryRun);
                setBusy(null);
                load();
                if (!dryRun)
                    onChanged();
            })
                .catch((err) => {
                setError(describe(err));
                setBusy(null);
            });
        }
        const cfg = status && status.config ? status.config : null;
        const preview = status && status.preview ? status.preview : { total: 0, items: [], errors: [] };
        const lastRun = status ? status.lastRun : null;
        const anyBusy = busy !== null;
        const statusLine = !loaded
            ? "加载中…"
            : [
                cfg && cfg.enabled ? "已启用" : "未启用",
                cfg ? "闲置 ≥ " + cfg.idleDays + " 天归档" : null,
                status && status.nextRunAt ? "下次扫描 " + fmtTime(status.nextRunAt) : null,
                lastRun ? "上次 " + fmtTime(lastRun.finishedAt) + " 归档 " + lastRun.archivedCount + " 个" : "尚未自动扫描过"
            ]
                .filter(Boolean)
                .join(" · ");
        const previewEl = showPreview ? (React.createElement("div", { className: "dsw-auto-preview" }, preview.total === 0 ? (React.createElement("div", { className: "dsw-auto-status" }, "\u5F53\u524D\u6CA1\u6709\u6EE1\u8DB3\u95F2\u7F6E\u6761\u4EF6\u7684\u4F1A\u8BDD\u3002")) : (React.createElement(React.Fragment, null,
            React.createElement("div", { className: "dsw-auto-status" },
                "\u5C06\u88AB\u5F52\u6863 ",
                preview.total,
                " \u4E2A\u4F1A\u8BDD",
                preview.items.length < preview.total ? "（仅显示前 " + preview.items.length + " 条）" : "",
                "\uFF1A"),
            preview.items.slice(0, 10).map((hit) => (React.createElement("div", { className: "dsw-auto-preview-item", key: hit.id },
                React.createElement("span", { className: "dsw-auto-preview-title" }, hit.title || hit.id),
                React.createElement("span", { className: "dsw-auto-preview-idle" },
                    "\u95F2\u7F6E ",
                    hit.idleDays,
                    " \u5929")))),
            preview.items.length > 10 ? (React.createElement("div", { className: "dsw-auto-status" },
                "\u2026\u53CA\u5176\u4ED6 ",
                preview.items.length - 10,
                " \u4E2A")) : null)))) : null;
        return (React.createElement("div", { className: "dsw-auto-card" },
            React.createElement("div", { className: "dsw-auto-head" },
                React.createElement("span", { className: "dsw-auto-title" }, "\u81EA\u52A8\u5F52\u6863"),
                React.createElement("label", { style: { display: "flex", alignItems: "center", gap: "4px", cursor: "pointer" } },
                    React.createElement("input", { type: "checkbox", checked: enabled, disabled: anyBusy, onChange: (e) => save(e.target.checked) }),
                    "\u542F\u7528"),
                React.createElement("span", null, "\u95F2\u7F6E"),
                React.createElement("input", { className: "dsw-auto-input", type: "number", min: "0.5", step: "0.5", value: idleDays, disabled: anyBusy, onChange: (e) => setIdleDays(e.target.value) }),
                React.createElement("span", null, "\u5929\u4EE5\u4E0A\u81EA\u52A8\u5F52\u6863 \u00B7 \u6BCF"),
                React.createElement("input", { className: "dsw-auto-input", type: "number", min: "0.25", step: "0.25", value: intervalDays, disabled: anyBusy, onChange: (e) => setIntervalDays(e.target.value) }),
                React.createElement("span", null, "\u5929\u626B\u63CF\u4E00\u6B21"),
                React.createElement("button", { className: "dsw-arch-btn", disabled: anyBusy, onClick: () => save(enabled) }, "\u4FDD\u5B58\u8BBE\u7F6E")),
            React.createElement("div", { className: "dsw-auto-status" }, statusLine),
            React.createElement("div", { className: "dsw-auto-status" }, "\u95F2\u7F6E\u6309\u4F1A\u8BDD\u6700\u540E\u6D3B\u8DC3\u65F6\u95F4\uFF08\u65E5\u5FD7\u6700\u540E\u5199\u5165\uFF09\u8BA1\u7B97\uFF0C\u975E\u4FA7\u8FB9\u680F\u663E\u793A\u7684\u521B\u5EFA\u65F6\u95F4\uFF1B\u7F6E\u9876\u4E0E\u624B\u52A8\u6392\u9664\u7684\u4F1A\u8BDD\u6C38\u4E0D\u81EA\u52A8\u5F52\u6863\u3002"),
            React.createElement("div", { className: "dsw-auto-row" },
                React.createElement("button", { className: "dsw-arch-btn", disabled: anyBusy, onClick: () => runScan(true) }, busy === "preview" ? "预览中…" : "立即扫描（仅预览）"),
                scanArmed ? (React.createElement(React.Fragment, null,
                    React.createElement("span", { className: "dsw-auto-status", style: { color: "var(--dsw-alias-state-warn-primary)" } }, "\u786E\u8BA4\u73B0\u5728\u5F52\u6863\u6240\u6709\u95F2\u7F6E\u4F1A\u8BDD\uFF1F"),
                    React.createElement("button", { className: "dsw-arch-btn dsw-arch-btn-danger", disabled: anyBusy, onClick: () => runScan(false) }, "\u786E\u8BA4\u5F52\u6863"),
                    React.createElement("button", { className: "dsw-arch-btn", disabled: anyBusy, onClick: () => setScanArmed(false) }, "\u53D6\u6D88"))) : (React.createElement("button", { className: "dsw-arch-btn", disabled: anyBusy, onClick: () => setScanArmed(true) }, busy === "scan" ? "扫描中…" : "立即扫描并归档"))),
            notice ? React.createElement("div", { className: "dsw-auto-status", style: { color: "var(--dsw-alias-state-success-primary, var(--dsw-alias-brand-primary))" } }, notice) : null,
            error ? React.createElement("div", { className: "dsw-arch-error" }, error) : null,
            previewEl,
            React.createElement("div", { className: "dsw-auto-row", style: { marginTop: "8px", borderTop: "1px solid var(--dsw-alias-border-l1)", paddingTop: "8px" } },
                React.createElement("button", { className: "dsw-arch-btn", disabled: sessBusy === "load", onClick: () => toggleSessions() }, showSessions ? "收起会话列表" : "手动归档 / 排除会话…"),
                showSessions && sessions !== null ? (React.createElement("span", { className: "dsw-auto-status" },
                    "\u5171 ",
                    sessions.length,
                    " \u4E2A\u672A\u5F52\u6863\u4F1A\u8BDD")) : null),
            showSessions ? (React.createElement("div", { className: "dsw-auto-sesslist" },
                sessions === null ? (React.createElement("div", { className: "dsw-auto-status" }, sessBusy === "load" ? "加载中…" : "")) : sessions.length === 0 ? (React.createElement("div", { className: "dsw-auto-status" }, "\u6CA1\u6709\u672A\u5F52\u6863\u7684\u4F1A\u8BDD\u3002")) : (sessions
                    .slice()
                    .sort((a, b) => {
                    if (a.wouldAutoArchive !== b.wouldAutoArchive)
                        return a.wouldAutoArchive ? -1 : 1;
                    return (b.idleDays ?? -1) - (a.idleDays ?? -1);
                })
                    .slice(0, 200)
                    .map((s) => {
                    const createdDays = daysAgo(s.createdAt);
                    return (React.createElement("div", { className: "dsw-auto-sess", key: s.id },
                        React.createElement("span", { className: "dsw-auto-sess-title", title: s.id },
                            s.title || s.id,
                            s.excluded ? "（已排除）" : "",
                            s.pinned ? "（已置顶）" : "",
                            s.running ? "（运行中）" : ""),
                        React.createElement("span", { className: "dsw-auto-sess-meta" },
                            createdDays !== null ? "创建 " + createdDays + " 天前 · " : "",
                            s.idleDays === null ? "闲置未知" : "闲置 " + s.idleDays + " 天",
                            s.wouldAutoArchive ? " · 将被自动归档" : ""),
                        React.createElement("span", { className: "dsw-auto-sess-btns" },
                            React.createElement("button", { className: "dsw-arch-btn", disabled: s.running || sessBusy !== null, onClick: () => archiveOneNow(s.id) }, sessBusy === "archive:" + s.id ? "归档中…" : "归档"),
                            s.excluded ? (React.createElement("button", { className: "dsw-arch-btn", disabled: sessBusy !== null, onClick: () => setExcludedNow(s.id, false) }, "\u53D6\u6D88\u6392\u9664")) : (React.createElement("button", { className: "dsw-arch-btn", disabled: sessBusy !== null, onClick: () => setExcludedNow(s.id, true) }, "\u6392\u9664")),
                            delArmId === s.id ? (React.createElement(React.Fragment, null,
                                React.createElement("span", { className: "dsw-auto-status", style: { color: "var(--dsw-alias-state-error-primary)" } }, "\u786E\u8BA4\u5220\u9664\uFF1F"),
                                React.createElement("button", { className: "dsw-arch-btn dsw-arch-btn-danger", disabled: sessBusy !== null, title: "\u4ECE\u786C\u76D8\u5220\u9664\u8BE5\u4F1A\u8BDD\u53CA\u5176\u65E5\u5FD7\uFF0C\u4E0D\u53EF\u6062\u590D\uFF085 \u79D2\u540E\u81EA\u52A8\u53D6\u6D88\uFF09", onClick: () => deleteOneNow(s.id) }, sessBusy === "delete:" + s.id ? "删除中…" : "确认删除"))) : (React.createElement("button", { className: "dsw-arch-btn dsw-arch-btn-danger", disabled: s.running || sessBusy !== null, title: "\u4ECE\u786C\u76D8\u5220\u9664\u8BE5\u4F1A\u8BDD\uFF08\u4E24\u6B65\u786E\u8BA4\uFF0C5 \u79D2\u540E\u81EA\u52A8\u53D6\u6D88\uFF09", onClick: () => armDelete(s.id) }, "\u5220\u9664")))));
                })),
                sessions !== null && sessions.length > 200 ? (React.createElement("div", { className: "dsw-auto-status" },
                    "\u4EC5\u663E\u793A\u524D 200 \u4E2A\uFF0C\u5171 ",
                    sessions.length,
                    " \u4E2A\u3002")) : null)) : null));
    }
    // ---------------------------------------------------------------------------
    // Attachment cleanup card
    // ---------------------------------------------------------------------------
    /**
     * Attachment store cleanup linked to session archiving. Lists files under
     * attachments/v1/objects that NO not-yet-archived session references (only
     * archived or already-deleted sessions used them) and offers a two-step
     * confirmed cleanup. Scan decompresses every live session log, so it takes
     * seconds — it never runs automatically.
     */
    function AttachmentCleanupCard() {
        const [status, setStatus] = React.useState(null);
        const [scanning, setScanning] = React.useState(false);
        const [armed, setArmed] = React.useState(false);
        const [cleaning, setCleaning] = React.useState(false);
        const [trashArmed, setTrashArmed] = React.useState(false);
        const [clearingTrash, setClearingTrash] = React.useState(false);
        const [notice, setNotice] = React.useState(null);
        const [error, setError] = React.useState(null);
        function describe(err) {
            if (err && typeof err === "object" && typeof err.message === "string") {
                return err.message;
            }
            return String(err);
        }
        function scan() {
            setScanning(true);
            setError(null);
            setNotice(null);
            setArmed(false);
            setTrashArmed(false);
            api("attachment-status", {})
                .then((res) => {
                setStatus(res);
                setScanning(false);
            })
                .catch((err) => {
                setError(describe(err));
                setScanning(false);
            });
        }
        function clean() {
            if (!status || status.unusedCount === 0)
                return;
            setCleaning(true);
            setError(null);
            setNotice(null);
            const shas = status.items.map((i) => i.sha);
            api("attachment-clean", { shas })
                .then((res) => {
                setNotice("已移入回收站 " + res.deleted + " 个附件（" + fmtSize(res.freedBytes) + "）；确认不再需要后可清空回收站" +
                    (res.errors && res.errors.length > 0 ? "；" + res.errors.length + " 个失败" : ""));
                setArmed(false);
                setCleaning(false);
                scan();
            })
                .catch((err) => {
                setError(describe(err));
                setCleaning(false);
            });
        }
        function clearTrash() {
            setClearingTrash(true);
            setError(null);
            setNotice(null);
            api("attachment-trash-clear", {})
                .then((res) => {
                setNotice("回收站已清空：彻底删除 " + res.files + " 个文件，释放 " + fmtSize(res.freedBytes));
                setTrashArmed(false);
                setClearingTrash(false);
                scan();
            })
                .catch((err) => {
                setError(describe(err));
                setClearingTrash(false);
            });
        }
        return (React.createElement("div", { className: "dsw-auto-card" },
            React.createElement("div", { className: "dsw-auto-head" },
                React.createElement("span", { className: "dsw-auto-title" }, "\u9644\u4EF6\u6E05\u7406"),
                React.createElement("span", { className: "dsw-auto-status" }, "\u627E\u51FA\u672A\u88AB\u4EFB\u4F55\u672A\u5F52\u6863\u4F1A\u8BDD\u53CA\u5176\u5386\u53F2\uFF08\u7EE7\u7EED\u4F1A\u8BDD\u7684\u8840\u7EDF\u94FE\uFF09\u5F15\u7528\u7684\u8D34\u56FE\u9644\u4EF6\uFF1B\u6E05\u7406 = \u79FB\u5165\u56DE\u6536\u7AD9\uFF0C\u53EF\u968F\u65F6\u624B\u52A8\u79FB\u56DE\uFF0C\u6E05\u7A7A\u56DE\u6536\u7AD9\u624D\u771F\u6B63\u5220\u9664")),
            React.createElement("div", { className: "dsw-auto-row" },
                React.createElement("button", { className: "dsw-arch-btn", disabled: scanning || clearingTrash, onClick: () => scan() }, scanning ? "扫描中…（全量解压会话日志，约十几秒）" : "扫描可清理附件"),
                status && status.available ? (React.createElement("span", { className: "dsw-auto-status" },
                    "\u9644\u4EF6\u5171 ",
                    status.totalFiles,
                    " \u4E2A / ",
                    fmtSize(status.totalBytes),
                    "\uFF1B\u53EF\u6E05\u7406",
                    " ",
                    React.createElement("strong", null,
                        status.unusedCount,
                        " \u4E2A / ",
                        fmtSize(status.unusedBytes)),
                    "\uFF08\u626B\u63CF ",
                    status.scannedSessions,
                    " \u4E2A\u4F1A\u8BDD \u00B7 ",
                    (status.durationMs / 1000).toFixed(1),
                    "s\uFF09",
                    status.trashFiles ? " · 回收站 " + status.trashFiles + " 个 / " + fmtSize(status.trashBytes || 0) : "")) : null,
                status && !status.available ? (React.createElement("span", { className: "dsw-auto-status" }, "\u672A\u627E\u5230 attachments/v1/objects \u76EE\u5F55\u3002")) : null),
            armed && status ? (React.createElement("div", { className: "dsw-auto-row" },
                React.createElement("span", { className: "dsw-auto-status", style: { color: "var(--dsw-alias-state-warn-primary)" } },
                    "\u628A ",
                    status.items.length,
                    " \u4E2A\u9644\u4EF6\uFF08",
                    fmtSize(status.unusedBytes),
                    "\uFF09\u79FB\u5165\u56DE\u6536\u7AD9\uFF1F\u79FB\u5165\u540E\u968F\u65F6\u53EF\u624B\u52A8\u79FB\u56DE objects \u76EE\u5F55\u6062\u590D\u3002"),
                React.createElement("button", { className: "dsw-arch-btn dsw-arch-btn-danger", disabled: cleaning, onClick: () => clean() }, cleaning ? "清理中…" : "确认移入回收站"),
                React.createElement("button", { className: "dsw-arch-btn", disabled: cleaning, onClick: () => setArmed(false) }, "\u53D6\u6D88"))) : null,
            status && status.unusedCount > 0 && !armed ? (React.createElement("div", { className: "dsw-auto-row" },
                React.createElement("button", { className: "dsw-arch-btn dsw-arch-btn-danger", disabled: cleaning, onClick: () => setArmed(true) },
                    "\u6E05\u7406\u8FD9 ",
                    status.unusedCount,
                    " \u4E2A\u9644\u4EF6\u2026"))) : null,
            status && status.trashFiles ? (React.createElement("div", { className: "dsw-auto-row" }, trashArmed ? (React.createElement(React.Fragment, null,
                React.createElement("span", { className: "dsw-auto-status", style: { color: "var(--dsw-alias-state-warn-primary)" } },
                    "\u786E\u8BA4\u5F7B\u5E95\u5220\u9664\u56DE\u6536\u7AD9\u91CC\u7684 ",
                    status.trashFiles,
                    " \u4E2A\u6587\u4EF6\uFF08",
                    fmtSize(status.trashBytes || 0),
                    "\uFF09\uFF1F\u6B64\u6B65\u4E4B\u540E\u4E0D\u53EF\u6062\u590D\u3002"),
                React.createElement("button", { className: "dsw-arch-btn dsw-arch-btn-danger", disabled: clearingTrash, onClick: () => clearTrash() }, clearingTrash ? "清空中…" : "确认清空"),
                React.createElement("button", { className: "dsw-arch-btn", disabled: clearingTrash, onClick: () => setTrashArmed(false) }, "\u53D6\u6D88"))) : (React.createElement("button", { className: "dsw-arch-btn", disabled: clearingTrash, onClick: () => setTrashArmed(true) },
                "\u6E05\u7A7A\u56DE\u6536\u7AD9\uFF08",
                status.trashFiles,
                " \u4E2A / ",
                fmtSize(status.trashBytes || 0),
                "\uFF09\u2026")))) : null,
            notice ? (React.createElement("div", { className: "dsw-auto-status", style: { color: "var(--dsw-alias-state-success-primary, var(--dsw-alias-brand-primary))" } }, notice)) : null,
            error ? React.createElement("div", { className: "dsw-arch-error" }, error) : null,
            status && status.items.length > 0 ? (React.createElement("div", { className: "dsw-auto-sesslist" },
                status.items.slice(0, 10).map((it) => (React.createElement("div", { className: "dsw-auto-sess", key: it.sha },
                    React.createElement("span", { className: "dsw-auto-sess-title", title: it.sha },
                        it.sha.slice(0, 16),
                        "\u2026"),
                    React.createElement("span", { className: "dsw-auto-sess-meta" },
                        fmtSize(it.sizeBytes),
                        " \u00B7 \u6700\u540E\u4FEE\u6539 ",
                        fmtTime(it.mtime))))),
                status.items.length > 10 ? (React.createElement("div", { className: "dsw-auto-status" },
                    "\u2026\u53CA\u5176\u4ED6 ",
                    status.items.length - 10,
                    " \u4E2A")) : null)) : null));
    }
    // ---------------------------------------------------------------------------
    // Page component
    // ---------------------------------------------------------------------------
    function ArchivedSessionsPage() {
        const [loading, setLoading] = React.useState(true);
        const [error, setError] = React.useState(null);
        const [items, setItems] = React.useState([]);
        const [total, setTotal] = React.useState(0);
        const [busy, setBusy] = React.useState(null);
        const [confirmId, setConfirmId] = React.useState(null);
        const [selected, setSelected] = React.useState([]);
        const [batchBusy, setBatchBusy] = React.useState(null);
        const [batchConfirm, setBatchConfirm] = React.useState(null);
        const [expandedId, setExpandedId] = React.useState(null);
        const [detail, setDetail] = React.useState(null);
        function describe(err) {
            if (err === null || err === undefined)
                return String(err);
            if (typeof err === "object" && typeof err.message === "string") {
                return err.message;
            }
            return String(err);
        }
        function applyList(res) {
            const next = res && Array.isArray(res.items) ? res.items : [];
            setItems(next);
            setTotal(res && typeof res.totalBytes === "number" ? res.totalBytes : 0);
            const ids = {};
            for (let i = 0; i < next.length; i++)
                ids[next[i].id] = true;
            setSelected((sel) => sel.filter((id) => ids[id]));
            if (expandedId && !ids[expandedId]) {
                setExpandedId(null);
                setDetail(null);
            }
        }
        function load() {
            setLoading(true);
            setError(null);
            api("list", {})
                .then((res) => {
                applyList(res);
                setLoading(false);
            })
                .catch((err) => {
                setError(describe(err));
                setLoading(false);
            });
        }
        React.useEffect(() => {
            load();
            // eslint-disable-next-line react-hooks/exhaustive-deps
        }, []);
        /**
       * Refresh the sidebar/workbench views.
       *
       * Nothing to do: the Workspace registry's `setState` lands in the storage
       * domain, which emits `domain/changed`; the host-side workspace feed turns that
       * into an `archived` frame on the browser's follow stream, so the sidebar
       * projection updates itself. (The client `workspaces` service is a subscribe +
       * snapshot model with no `refresh()` to call.)
       */
        function refreshViews() { }
        function reloadAfterAction() {
            refreshViews();
            return api("list", {}).then(applyList);
        }
        // ---- row operations ----
        function unarchive(id) {
            setBusy("unarchive:" + id);
            setError(null);
            api("unarchive", { sessionId: id })
                .then(() => reloadAfterAction())
                .catch((err) => setError(describe(err)))
                .finally(() => setBusy(null));
        }
        // Single-button two-step delete: 删除 -> 确认 (auto-reverts after 5s).
        //
        // The browser timer globals are available to a plugin bundle (only dynamic
        // packages are guarded), and the host-side timer plugin is not on the browser
        // context, so a native timeout is the right tool here.
        function armDelete(id) {
            setConfirmId(id);
            try {
                window.setTimeout(() => {
                    setConfirmId((cur) => (cur === id ? null : cur));
                }, 5000);
            }
            catch (e) {
                // timer unavailable; stay armed until the user acts
            }
        }
        function doDelete(id) {
            setBusy("delete:" + id);
            setError(null);
            api("delete", { sessionId: id })
                .then(() => reloadAfterAction())
                .catch((err) => setError(describe(err)))
                .finally(() => {
                setBusy(null);
                setConfirmId(null);
            });
        }
        // ---- selection ----
        function toggleSelect(id) {
            setSelected((sel) => (sel.includes(id) ? sel.filter((x) => x !== id) : sel.concat([id])));
        }
        function toggleSelectAll() {
            setSelected((sel) => (sel.length === items.length ? [] : items.map((item) => item.id)));
        }
        // ---- batch operations ----
        async function runBatch(ids, kind) {
            setBatchBusy(kind);
            setError(null);
            const results = [];
            const method = kind === "delete" ? "delete" : "unarchive";
            for (const id of ids) {
                try {
                    await api(method, { sessionId: id });
                    results.push({ id, ok: true });
                }
                catch (err) {
                    results.push({ id, ok: false });
                }
            }
            const failed = results.filter((r) => !r.ok);
            if (failed.length > 0) {
                setError((kind === "delete" ? "删除" : "释放") +
                    "失败 " + failed.length + " 个会话：" + failed.map((f) => f.id).join(", "));
            }
            refreshViews();
            try {
                applyList(await api("list", {}));
            }
            catch (err) {
                setError(describe(err));
            }
            finally {
                setBatchBusy(null);
                setBatchConfirm(null);
                setSelected([]);
                setConfirmId(null);
            }
        }
        function releaseAll() {
            runBatch(items.map((item) => item.id), "unarchive");
        }
        function clearAll() {
            runBatch(items.map((item) => item.id), "delete");
        }
        function releaseSelected() {
            runBatch(selected, "unarchive");
        }
        function deleteSelected() {
            runBatch(selected, "delete");
        }
        // ---- detail ----
        function toggleDetail(id) {
            if (expandedId === id) {
                setExpandedId(null);
                setDetail(null);
                return;
            }
            setExpandedId(id);
            setDetail({ id, loading: true, data: null, error: null });
            api("detail", { sessionId: id })
                .then((data) => {
                setDetail({ id, loading: false, data, error: null });
            })
                .catch((err) => {
                setDetail({ id, loading: false, data: null, error: describe(err) });
            });
        }
        function detailCell() {
            if (!detail)
                return null;
            if (detail.loading) {
                return React.createElement("div", { className: "dsw-arch-detail" }, "\u52A0\u8F7D\u4F1A\u8BDD\u5185\u5BB9\u4E2D\u2026");
            }
            if (detail.error) {
                return React.createElement("div", { className: "dsw-arch-detail" }, detail.error);
            }
            const d = detail.data;
            if (!d || !Array.isArray(d.messages)) {
                return React.createElement("div", { className: "dsw-arch-detail" }, "\u6CA1\u6709\u53EF\u663E\u793A\u7684\u5185\u5BB9");
            }
            const headParts = [];
            if (d.createdAt)
                headParts.push("创建于 " + fmtTime(d.createdAt));
            if (d.cwd)
                headParts.push(d.cwd);
            const msgs = d.messages.map((m, i) => {
                const roleLabel = m.role === "user" ? "用户" : m.role === "assistant" ? "助手" : "工具";
                return (React.createElement("div", { key: i, className: "dsw-arch-msg dsw-arch-msg-" + m.role },
                    React.createElement("span", { className: "dsw-arch-msg-role" }, roleLabel),
                    React.createElement("span", { className: "dsw-arch-msg-time" }, fmtTime(m.time)),
                    React.createElement("div", null, m.text)));
            });
            return (React.createElement("div", { className: "dsw-arch-detail" },
                React.createElement("div", { className: "dsw-arch-detail-head" },
                    React.createElement("span", { className: "dsw-arch-page-title" }, "\u4F1A\u8BDD\u5185\u5BB9"),
                    React.createElement("span", { className: "dsw-arch-meta" },
                        " \u00B7 ",
                        headParts.join(" · "))),
                React.createElement("div", { className: "dsw-arch-detail-note" },
                    "\u5171 ",
                    d.totalEvents,
                    " \u6761\u4E8B\u4EF6\uFF0C\u63D0\u53D6 ",
                    d.messageCount,
                    " \u6761\u6D88\u606F",
                    d.truncated ? "（仅显示前 100 条）" : ""),
                React.createElement("div", { className: "dsw-arch-detail-body" }, msgs)));
        }
        // ---- render ----
        const anyBusy = busy !== null || batchBusy !== null;
        const header = (React.createElement("div", { className: "dsw-arch-toolbar" },
            React.createElement("span", { className: "dsw-arch-page-title" }, "\u5F52\u6863\u4F1A\u8BDD"),
            React.createElement("span", { className: "dsw-arch-meta" },
                items.length,
                " \u4E2A\u4F1A\u8BDD \u00B7 \u5171 ",
                fmtSize(total),
                loading ? " · 加载中…" : "",
                batchBusy ? " · 批量操作中…" : ""),
            React.createElement("button", { className: "dsw-arch-btn", disabled: anyBusy, onClick: () => load() }, "\u5237\u65B0"),
            React.createElement("button", { className: "dsw-arch-btn", disabled: anyBusy || items.length === 0, onClick: () => releaseAll() }, "\u4E00\u952E\u91CA\u653E"),
            React.createElement("button", { className: "dsw-arch-btn dsw-arch-btn-danger", disabled: anyBusy || items.length === 0, onClick: () => setBatchConfirm("clear") }, "\u4E00\u952E\u6E05\u7A7A")));
        let confirmBar = null;
        if (batchConfirm === "clear") {
            confirmBar = (React.createElement("div", { className: "dsw-arch-selectbar" },
                React.createElement("span", { className: "dsw-arch-meta", style: { color: "var(--dsw-alias-state-warn-primary)" } },
                    "\u786E\u8BA4\u6E05\u7A7A\u5168\u90E8 ",
                    items.length,
                    " \u4E2A\u5F52\u6863\u4F1A\u8BDD\uFF1F\u6B64\u64CD\u4F5C\u4F1A\u4ECE\u786C\u76D8\u5220\u9664\u4E14\u4E0D\u53EF\u6062\u590D\u3002"),
                React.createElement("button", { className: "dsw-arch-btn dsw-arch-btn-danger", disabled: anyBusy, onClick: () => clearAll() }, "\u786E\u8BA4\u6E05\u7A7A"),
                React.createElement("button", { className: "dsw-arch-btn", disabled: anyBusy, onClick: () => setBatchConfirm(null) }, "\u53D6\u6D88")));
        }
        else if (batchConfirm === "delete") {
            confirmBar = (React.createElement("div", { className: "dsw-arch-selectbar" },
                React.createElement("span", { className: "dsw-arch-meta", style: { color: "var(--dsw-alias-state-warn-primary)" } },
                    "\u786E\u8BA4\u5220\u9664\u9009\u4E2D\u7684 ",
                    selected.length,
                    " \u4E2A\u4F1A\u8BDD\uFF1F\u6B64\u64CD\u4F5C\u4E0D\u53EF\u6062\u590D\u3002"),
                React.createElement("button", { className: "dsw-arch-btn dsw-arch-btn-danger", disabled: anyBusy, onClick: () => deleteSelected() }, "\u786E\u8BA4\u5220\u9664"),
                React.createElement("button", { className: "dsw-arch-btn", disabled: anyBusy, onClick: () => setBatchConfirm(null) }, "\u53D6\u6D88")));
        }
        else if (selected.length > 0) {
            confirmBar = (React.createElement("div", { className: "dsw-arch-selectbar" },
                React.createElement("span", { className: "dsw-arch-meta" },
                    "\u5DF2\u9009\u62E9 ",
                    selected.length,
                    " \u4E2A\u4F1A\u8BDD"),
                React.createElement("button", { className: "dsw-arch-btn", disabled: anyBusy, onClick: () => releaseSelected() }, "\u91CA\u653E\u9009\u4E2D"),
                React.createElement("button", { className: "dsw-arch-btn dsw-arch-btn-danger", disabled: anyBusy, onClick: () => setBatchConfirm("delete") }, "\u5220\u9664\u9009\u4E2D"),
                React.createElement("button", { className: "dsw-arch-btn", disabled: anyBusy, onClick: () => setSelected([]) }, "\u53D6\u6D88\u9009\u62E9")));
        }
        let body;
        if (loading && items.length === 0) {
            body = React.createElement("div", { className: "dsw-arch-empty" }, "\u52A0\u8F7D\u4E2D\u2026");
        }
        else if (items.length === 0) {
            body = React.createElement("div", { className: "dsw-arch-empty" }, "\u6CA1\u6709\u5DF2\u5F52\u6863\u7684\u4F1A\u8BDD");
        }
        else {
            const allSelected = selected.length === items.length;
            const rows = items.map((item) => {
                const confirming = confirmId === item.id;
                const metaParts = [];
                if (item.createdAt)
                    metaParts.push("创建于 " + fmtTime(item.createdAt));
                if (item.cwd)
                    metaParts.push(item.cwd);
                const chevron = expandedId === item.id ? "▾ " : "▸ ";
                return (React.createElement(React.Fragment, { key: item.id },
                    React.createElement("tr", null,
                        React.createElement("td", null,
                            React.createElement("input", { type: "checkbox", checked: selected.includes(item.id), disabled: anyBusy, onChange: () => toggleSelect(item.id) })),
                        React.createElement("td", null,
                            React.createElement("div", { className: "dsw-arch-title-click", title: "\u70B9\u51FB\u67E5\u770B\u4F1A\u8BDD\u5185\u5BB9", onClick: () => toggleDetail(item.id) },
                                chevron,
                                item.title || "(无标题)"),
                            React.createElement("div", { className: "dsw-arch-id" }, item.id),
                            React.createElement("div", { className: "dsw-arch-meta" }, metaParts.join(" · ")),
                            item.path ? React.createElement("div", { className: "dsw-arch-path" }, item.path) : null),
                        React.createElement("td", null, item.missing ? (React.createElement("span", { className: "dsw-arch-badge" }, "\u6587\u4EF6\u7F3A\u5931")) : (React.createElement("span", { className: "dsw-arch-size" }, fmtSize(item.sizeBytes)))),
                        React.createElement("td", { className: "dsw-arch-actions" },
                            React.createElement("button", { className: "dsw-arch-btn", disabled: anyBusy || item.missing, onClick: () => unarchive(item.id) }, "\u91CA\u653E"),
                            React.createElement("button", { className: "dsw-arch-btn dsw-arch-btn-danger", disabled: anyBusy, title: confirming ? "再次点击确认删除（5 秒后自动取消）" : "删除（需再次点击确认）", onClick: () => (confirming ? doDelete(item.id) : armDelete(item.id)) }, confirming ? "确认" : "删除"))),
                    expandedId === item.id ? (React.createElement("tr", { key: item.id + "-detail" },
                        React.createElement("td", { colSpan: 4, style: { padding: "4px 10px 10px" } }, detailCell()))) : null));
            });
            body = (React.createElement("table", { className: "dsw-arch-table" },
                React.createElement("thead", null,
                    React.createElement("tr", null,
                        React.createElement("th", null,
                            React.createElement("input", { type: "checkbox", checked: allSelected, disabled: anyBusy, onChange: () => toggleSelectAll() })),
                        React.createElement("th", null, "\u4F1A\u8BDD"),
                        React.createElement("th", null, "\u78C1\u76D8\u5360\u7528"),
                        React.createElement("th", null, "\u64CD\u4F5C"))),
                React.createElement("tbody", null, rows)));
        }
        const errorEl = error ? React.createElement("div", { className: "dsw-arch-error" }, error) : null;
        return (React.createElement("div", { className: "dsw-arch-page" },
            React.createElement("style", null, CSS),
            errorEl,
            React.createElement(AutoArchiveCard, { onChanged: load }),
            React.createElement(AttachmentCleanupCard, null),
            header,
            confirmBar,
            body));
    }
    // ---------------------------------------------------------------------------
    // Plugin body
    // ---------------------------------------------------------------------------
    /**
     * Client-side service dependencies.
     *
     * `slots` (ui-renderer) is the registration seat. `workspaces`
     * (api-workspace-controller) is the live Workspace/archive projection the page
     * is about — it is injectable on 0.1.5-rc.1 and worth waiting for.
     *
     * Dropped from the original list: `sessions` (provided via
     * `ctx.reflect.provide`, not a Cordis service, so it is not injectable) and
     * `timer` (the page now uses a native `setTimeout`; the host-side timer plugin
     * is not on the browser context).
     */
    exports.inject = ["slots", "workspaces"];
    function apply(ctx) {
        ctx.slots.inject("settings.section", () => ctx.slots.register({ name: "settings.section", id: "archived-sessions", order: 30, label: () => "归档会话" }, () => React.createElement(ArchivedSessionsPage)));
    }
    return module.exports;
  }
});
