/**
 * Wraps the tsc-compiled (CommonJS) client module into the __ModuleLoader__
 * bundle shape the harness browser runtime expects:
 *
 *   window.__ModuleLoader__.load({ id, factory: (require) => { ... } })
 *
 * The compiled body may use `exports` and `require("react")` freely because
 * both are in scope inside the factory (`var exports = module.exports` and the
 * factory's `require` parameter).
 *
 * Run via `npm run build` after `tsc -p tsconfig.client.json`.
 */
import { readFileSync, writeFileSync, rmSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = dirname(dirname(fileURLToPath(import.meta.url)));
const tmpDir = join(root, "lib", ".client");
const compiled = readFileSync(join(tmpDir, "client.js"), "utf8").trim();

// Indent the compiled body so the wrapped output stays readable.
const indented = compiled
  .split("\n")
  .map((line) => (line.length ? "    " + line : line))
  .join("\n");

const out =
  "// Generated by scripts/build-client.mjs from src/client.tsx — do not edit.\n" +
  "window.__ModuleLoader__.load({\n" +
  '  id: "dsh-auto-archive",\n' +
  "  factory: (require) => {\n" +
  "    var module = { exports: {} };\n" +
  "    var exports = module.exports;\n" +
  '    Object.defineProperty(exports, Symbol.toStringTag, { value: "Module" });\n' +
  indented +
  "\n" +
  "    return module.exports;\n" +
  "  }\n" +
  "});\n";

writeFileSync(join(root, "lib", "client.js"), out);
rmSync(tmpDir, { recursive: true, force: true });
console.log("lib/client.js written (" + out.length + " bytes)");
